name: Sync to personal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        run: |
          git clone --branch main https://PegasisForever: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@github.com/PegasisForever/github_action_test.git
          cd github_action_test
          git status
          git push https://PegasisForever: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@github.com/PegasisForever/github_action_test_public.git --set-upstream main
